### ISSUE TITLE
`data` event is not called

### ISSUE THREAD

**Issue by superdinmc** [replit/ruspty#39]
I have been debugging my code for few hours now wondering why it is not calling, I have made this repl snippet:
```js
const { Pty } = require('@replit/ruspty');
const proc = new Pty({command:`docker`,args:['attach','Nebula'],onExit(){console.log('exit')}});
proc.read.on('data',dat=>console.log(dat.toString()));
```
This one triggers perfectly normal in node.js, but not bun repl(and bun itself, the real code)

My production code looks like the following:
```js
  console.log('Attach')
  const proc = new Pty({
    command: `docker`,
    args: ["attach", id],
    onExit() {console.log('Close')},
    interactive: true,
    size: {
      cols: 40,
      rows: 30,
    }
  });
  proc.read.on('data', dat => {
    console.log('Data');
    ws.sendBinary(dat);
  });
  proc.read.on('readable', () => {
    console.log('Readable');
    const res = proc.read.read();
    console.log(res.toString());
    ws.sendBinary(res);
  })
```
In bun, `Readable` logs when I `.close()` the pty, but then `read()` returns null so it thrown error on `res.toString()`. not a single `Data` is logged.

**Comment by lhchavez** [comment]
we dropped support for bun in https://github.com/replit/ruspty/commit/e5e7c6f4830d79aecb0e5fc6066c4f534f62b20e (a.k.a. 3.0.0) :(

**Comment by superdinmc** [comment]
Well I have found workaround by summoning node worker to do it instead, so I guess I'll stay with that now

**Comment by lhchavez** [comment]
yeah, we're fans of bun, but there are still a few incompatibilities here and there. they're committed to compatibility so it'll happen at some point!
